language: python
python:
- '3.6'
install: skip
jobs:
  include:
  - stage: unittest
    name: Unit tests
    before_script:
    - pip install -r requirements-dev.txt
    - pip install coveralls
    script: bolt cov
    after_success: coveralls
deploy:
  provider: pypi
  username: __token__
  password:
    secure: EiDr2gDWG/VtNRf7waVoGO6C6rBWCqcvPgFjwfZd8dSqlw4EoEjVC7sCs+COz3/xupGkHSLNIjHrfHUUZ97eDLX3z+Y/Oy2tFH5nAqNhTjA6QfhgtYgu9X/1d+SaxDnfOlA7KJk0xZOsdbhN6HQ3smqox05yEKl5wKg3xQJfY8kbd8S+lFCoY1qoWCHuiunRwreR7+KuKm+cstM0wAHjX6YG+zva7CTGTpTTmXqB8G5cuCnNdHAuyRagg+cwWarxxSzDfpsx6pzQ03mWwO7KEI2s9nSFf4dPtRsl8QSZwt5TMv3GsYq4QfhuskcC5Wi4nMGIIeHwmerGz78S2c4b71RpCe1CghQOfEkXw2rjKrZz6L2b9lk+Sa/A+KSRnFkCdhQSMtP7iuwRHbpjDhm422oLCT9hHmkc5PbueezWBzjruR8E9SEUR+/7C2XQbqD0rnGtByzPmge7eZv6ZjawWcA1kUqpI3dzdWwu3D89KAYnPbj+mFL7xhVmno40O3e6UDHU9Hgcmm1S1L4wy9OzO1EP5yjTcrY9iUb1DwqNjShQHL3r/+2qwAIx3TzcQS+j0MGBlk59rz4FpDsExSrplSu4qwGC/JHAfaZQ+P14jjMjM6j4baoV77UDok+H04ZjO5YlmfBNvFtWcirMsl4HV8N+BJ2QIY/VkQPi+WdshDg=
  on:
    branch: master
  distributions: sdist bdist_wheel
  skip_existing: true
