name: run-unit-tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync -p 3.11
      - name: unittest
        run: uv run pytest tests/unit
